// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfi3eKzDBTSBwDXIKu2NKvxpmjxDSveTU',
    appId: '1:711008762713:web:57ff3324317ff0f34e2a48',
    messagingSenderId: '711008762713',
    projectId: 'cinemaster-1de4f',
    authDomain: 'cinemaster-1de4f.firebaseapp.com',
    storageBucket: 'cinemaster-1de4f.appspot.com',
    measurementId: 'G-2B348Z2EBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8cxb0KEeeoujLHWFTHRHmM0dyzRa-mU',
    appId: '1:711008762713:android:5410930ee2a8b1324e2a48',
    messagingSenderId: '711008762713',
    projectId: 'cinemaster-1de4f',
    storageBucket: 'cinemaster-1de4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUR1RV0cp5g0DmPRhqWzdmjJjdxQsn04s',
    appId: '1:711008762713:ios:df17515d1a2e366d4e2a48',
    messagingSenderId: '711008762713',
    projectId: 'cinemaster-1de4f',
    storageBucket: 'cinemaster-1de4f.appspot.com',
    iosBundleId: 'com.example.cinemasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUR1RV0cp5g0DmPRhqWzdmjJjdxQsn04s',
    appId: '1:711008762713:ios:df17515d1a2e366d4e2a48',
    messagingSenderId: '711008762713',
    projectId: 'cinemaster-1de4f',
    storageBucket: 'cinemaster-1de4f.appspot.com',
    iosBundleId: 'com.example.cinemasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfi3eKzDBTSBwDXIKu2NKvxpmjxDSveTU',
    appId: '1:711008762713:web:73b68be9570e6c884e2a48',
    messagingSenderId: '711008762713',
    projectId: 'cinemaster-1de4f',
    authDomain: 'cinemaster-1de4f.firebaseapp.com',
    storageBucket: 'cinemaster-1de4f.appspot.com',
    measurementId: 'G-MVD4BC8FM3',
  );

}